namespace DataAccessLayer.Models
{
    public class ItemDAO
    {
        public int Num;
        public string strName;
        public byte Kind;
        public byte Slot;
        public byte Race;
        public byte Class;
        public short Damage;
        public short Delay;
        public short Range;
        public short Weight;
        public short Duration;
        public int BuyPrice;
        public int SellPrice;
        public short Ac;
        public byte Countable;
        public int Effect1;
        public int Effect2;
        public byte ReqLevel;
        public byte ReqLevelMax;
        public byte ReqRank;
        public byte ReqTitle;
        public byte ReqStr;
        public byte ReqSta;
        public byte ReqDex;
        public byte ReqIntel;
        public byte ReqCha;
        public byte SellingGroup;
        public byte ItemType;
        public short Hitrate;
        public short Evasionrate;
        public short DaggerAc;
        public short SwordAc;
        public short MaceAc;
        public short AxeAc;
        public short SpearAc;
        public short BowAc;
        public byte FireDamage;
        public byte IceDamage;
        public byte LightningDamage;
        public byte PoisonDamage;
        public byte HPDrain;
        public byte MPDamage;
        public byte MPDrain;
        public byte MirrorDamage;
        public byte Droprate;
        public short StrB;
        public short StaB;
        public short DexB;
        public short IntelB;
        public short ChaB;
        public short MaxHpB;
        public short MaxMpB;
        public short FireR;
        public short ColdR;
        public short LightningR;
        public short MagicR;
        public short PoisonR;
        public short CurseR;
    }
}
