//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableEditor.Resources.LangEn", typeof(LangEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string frmColumnEditor_Button_Add {
            get {
                return ResourceManager.GetString("frmColumnEditor_Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove checked.
        /// </summary>
        internal static string frmColumnEditor_Button_RemoveChecked {
            get {
                return ResourceManager.GetString("frmColumnEditor_Button_RemoveChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string frmColumnEditor_Button_Update {
            get {
                return ResourceManager.GetString("frmColumnEditor_Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Column.
        /// </summary>
        internal static string frmColumnEditor_GroupBox_EditColumn {
            get {
                return ResourceManager.GetString("frmColumnEditor_GroupBox_EditColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Column.
        /// </summary>
        internal static string frmColumnEditor_GroupBox_NewColumn {
            get {
                return ResourceManager.GetString("frmColumnEditor_GroupBox_NewColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New data type :.
        /// </summary>
        internal static string frmColumnEditor_Label_ChangeDataType {
            get {
                return ResourceManager.GetString("frmColumnEditor_Label_ChangeDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type :.
        /// </summary>
        internal static string frmColumnEditor_Label_DataType {
            get {
                return ResourceManager.GetString("frmColumnEditor_Label_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value :.
        /// </summary>
        internal static string frmColumnEditor_Label_DefaultValue {
            get {
                return ResourceManager.GetString("frmColumnEditor_Label_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing columns of table : {0}.
        /// </summary>
        internal static string frmColumnEditor_Title {
            get {
                return ResourceManager.GetString("frmColumnEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check all columns.
        /// </summary>
        internal static string frmExportAsSQL_Button_CheckAllColumns {
            get {
                return ResourceManager.GetString("frmExportAsSQL_Button_CheckAllColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export selected columns as insert query.
        /// </summary>
        internal static string frmExportAsSQL_Button_Export {
            get {
                return ResourceManager.GetString("frmExportAsSQL_Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck all columns.
        /// </summary>
        internal static string frmExportAsSQL_Button_UncheckAllColumns {
            get {
                return ResourceManager.GetString("frmExportAsSQL_Button_UncheckAllColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop if any previous table with same name exists (DROP TABLE).
        /// </summary>
        internal static string frmExportAsSQL_CheckBox_DropPrevious {
            get {
                return ResourceManager.GetString("frmExportAsSQL_CheckBox_DropPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export CREATE TABLE query of the table.
        /// </summary>
        internal static string frmExportAsSQL_CheckBox_IncludeCreate {
            get {
                return ResourceManager.GetString("frmExportAsSQL_CheckBox_IncludeCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truncate target table (TRUNCATE).
        /// </summary>
        internal static string frmExportAsSQL_CheckBox_Truncate {
            get {
                return ResourceManager.GetString("frmExportAsSQL_CheckBox_Truncate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured query language files (*.sql)|*.sql.
        /// </summary>
        internal static string frmExportAsSQL_Filter {
            get {
                return ResourceManager.GetString("frmExportAsSQL_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table options.
        /// </summary>
        internal static string frmExportAsSQL_GroupBox_TableOptions {
            get {
                return ResourceManager.GetString("frmExportAsSQL_GroupBox_TableOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column names.
        /// </summary>
        internal static string frmExportAsSQL_Label_ColumnNames {
            get {
                return ResourceManager.GetString("frmExportAsSQL_Label_ColumnNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        internal static string frmExportAsSQL_Label_Columns {
            get {
                return ResourceManager.GetString("frmExportAsSQL_Label_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name.
        /// </summary>
        internal static string frmExportAsSQL_Label_TableName {
            get {
                return ResourceManager.GetString("frmExportAsSQL_Label_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mini-tool allows you to export table files as SQL queries, so you can import any kind of data from them. Select the columns that you need, then name them(optional). Specify a table name(that will be used for generating INSERT INTO and CREATE TABLE target table names). Then, just press &apos;export&apos; button..
        /// </summary>
        internal static string frmExportAsSQL_TextBox_Description {
            get {
                return ResourceManager.GetString("frmExportAsSQL_TextBox_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export table as SQL Query : {0}.
        /// </summary>
        internal static string frmExportAsSQL_Title {
            get {
                return ResourceManager.GetString("frmExportAsSQL_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string frmFindAndReplace_Button_Close {
            get {
                return ResourceManager.GetString("frmFindAndReplace_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace all.
        /// </summary>
        internal static string frmFindAndReplace_Button_ReplaceAll {
            get {
                return ResourceManager.GetString("frmFindAndReplace_Button_ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace next .
        /// </summary>
        internal static string frmFindAndReplace_Button_ReplaceNext {
            get {
                return ResourceManager.GetString("frmFindAndReplace_Button_ReplaceNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case sensitive.
        /// </summary>
        internal static string frmFindAndReplace_CheckBox_CaseSensitive {
            get {
                return ResourceManager.GetString("frmFindAndReplace_CheckBox_CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match whole.
        /// </summary>
        internal static string frmFindAndReplace_CheckBox_MatchWhole {
            get {
                return ResourceManager.GetString("frmFindAndReplace_CheckBox_MatchWhole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find what:.
        /// </summary>
        internal static string frmFindAndReplace_Label_FindWhat {
            get {
                return ResourceManager.GetString("frmFindAndReplace_Label_FindWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with:.
        /// </summary>
        internal static string frmFindAndReplace_Label_ReplaceWith {
            get {
                return ResourceManager.GetString("frmFindAndReplace_Label_ReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and Replace.
        /// </summary>
        internal static string frmFindAndReplace_Title {
            get {
                return ResourceManager.GetString("frmFindAndReplace_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading main interface, be patient.
        /// </summary>
        internal static string frmLoading_PP_Description {
            get {
                return ResourceManager.GetString("frmLoading_PP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        internal static string frmLoading_PP_Title {
            get {
                return ResourceManager.GetString("frmLoading_PP_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select destination...
        /// </summary>
        internal static string frmSaveAs_Button_SaveAs {
            get {
                return ResourceManager.GetString("frmSaveAs_Button_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method description.
        /// </summary>
        internal static string frmSaveAs_Label_Description {
            get {
                return ResourceManager.GetString("frmSaveAs_Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption method :.
        /// </summary>
        internal static string frmSaveAs_Label_Method {
            get {
                return ResourceManager.GetString("frmSaveAs_Label_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as...
        /// </summary>
        internal static string frmSaveAs_Title {
            get {
                return ResourceManager.GetString("frmSaveAs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string mainFrm_LanguageLabel {
            get {
                return ResourceManager.GetString("mainFrm_LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About...
        /// </summary>
        internal static string mainFrm_Menu_About {
            get {
                return ResourceManager.GetString("mainFrm_Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by &lt;href=http://insomniacoder.blogspot.com&gt;PENTAGRAM&lt;/href&gt;.
        /// </summary>
        internal static string mainFrm_Menu_About_Author {
            get {
                return ResourceManager.GetString("mainFrm_Menu_About_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (C) 2017.
        /// </summary>
        internal static string mainFrm_Menu_About_Copyright {
            get {
                return ResourceManager.GetString("mainFrm_Menu_About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knight OnLine table editor.
        /// </summary>
        internal static string mainFrm_Menu_About_Program {
            get {
                return ResourceManager.GetString("mainFrm_Menu_About_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.3.
        /// </summary>
        internal static string mainFrm_Menu_About_Version {
            get {
                return ResourceManager.GetString("mainFrm_Menu_About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string mainFrm_Menu_Edit {
            get {
                return ResourceManager.GetString("mainFrm_Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column editor.
        /// </summary>
        internal static string mainFrm_Menu_Edit_ColumnEditor {
            get {
                return ResourceManager.GetString("mainFrm_Menu_Edit_ColumnEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New row.
        /// </summary>
        internal static string mainFrm_Menu_Edit_NewRow {
            get {
                return ResourceManager.GetString("mainFrm_Menu_Edit_NewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Copy.
        /// </summary>
        internal static string mainFrm_Menu_Edit_RowCopy {
            get {
                return ResourceManager.GetString("mainFrm_Menu_Edit_RowCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Delete.
        /// </summary>
        internal static string mainFrm_Menu_Edit_RowDelete {
            get {
                return ResourceManager.GetString("mainFrm_Menu_Edit_RowDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Paste.
        /// </summary>
        internal static string mainFrm_Menu_Edit_RowPaste {
            get {
                return ResourceManager.GetString("mainFrm_Menu_Edit_RowPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string mainFrm_Menu_File {
            get {
                return ResourceManager.GetString("mainFrm_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk convert.
        /// </summary>
        internal static string mainFrm_Menu_File_BulkConvert {
            get {
                return ResourceManager.GetString("mainFrm_Menu_File_BulkConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string mainFrm_Menu_File_Logout {
            get {
                return ResourceManager.GetString("mainFrm_Menu_File_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open table.
        /// </summary>
        internal static string mainFrm_Menu_File_Open {
            get {
                return ResourceManager.GetString("mainFrm_Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save table.
        /// </summary>
        internal static string mainFrm_Menu_File_Save {
            get {
                return ResourceManager.GetString("mainFrm_Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save table as...
        /// </summary>
        internal static string mainFrm_Menu_File_SaveAs {
            get {
                return ResourceManager.GetString("mainFrm_Menu_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Export.
        /// </summary>
        internal static string mainFrm_Menu_File_SqlExport {
            get {
                return ResourceManager.GetString("mainFrm_Menu_File_SqlExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Information.
        /// </summary>
        internal static string mainFrm_Menu_FInfo {
            get {
                return ResourceManager.GetString("mainFrm_Menu_FInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column count.
        /// </summary>
        internal static string mainFrm_Menu_FInfo_ColumnCount {
            get {
                return ResourceManager.GetString("mainFrm_Menu_FInfo_ColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        internal static string mainFrm_Menu_FInfo_Created {
            get {
                return ResourceManager.GetString("mainFrm_Menu_FInfo_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption method.
        /// </summary>
        internal static string mainFrm_Menu_FInfo_Encryption {
            get {
                return ResourceManager.GetString("mainFrm_Menu_FInfo_Encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string mainFrm_Menu_FInfo_Filename {
            get {
                return ResourceManager.GetString("mainFrm_Menu_FInfo_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last access time.
        /// </summary>
        internal static string mainFrm_Menu_FInfo_LastAccess {
            get {
                return ResourceManager.GetString("mainFrm_Menu_FInfo_LastAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified.
        /// </summary>
        internal static string mainFrm_Menu_FInfo_LastModify {
            get {
                return ResourceManager.GetString("mainFrm_Menu_FInfo_LastModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string mainFrm_Menu_FInfo_Path {
            get {
                return ResourceManager.GetString("mainFrm_Menu_FInfo_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row count.
        /// </summary>
        internal static string mainFrm_Menu_FInfo_RowCount {
            get {
                return ResourceManager.GetString("mainFrm_Menu_FInfo_RowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string mainFrm_Menu_FInfo_Size {
            get {
                return ResourceManager.GetString("mainFrm_Menu_FInfo_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string mainFrm_Menu_Search {
            get {
                return ResourceManager.GetString("mainFrm_Menu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string mainFrm_Menu_Search_Find {
            get {
                return ResourceManager.GetString("mainFrm_Menu_Search_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find &amp; Replace.
        /// </summary>
        internal static string mainFrm_Menu_Search_FindAndReplace {
            get {
                return ResourceManager.GetString("mainFrm_Menu_Search_FindAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knight OnLine Table Editor :: PENTAGRAM, 2017, KODEVELOPERS EDITION.
        /// </summary>
        internal static string mainFrm_Title {
            get {
                return ResourceManager.GetString("mainFrm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as : {0}.
        /// </summary>
        internal static string mainFrm_User {
            get {
                return ResourceManager.GetString("mainFrm_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version : 1.3.
        /// </summary>
        internal static string mainFrm_Version {
            get {
                return ResourceManager.GetString("mainFrm_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was error(s) during copy operation.\nEither column count does not match with source table, or data type mismatch.\nCopied {0} out of {1} row(s)..
        /// </summary>
        internal static string Message_CopyError {
            get {
                return ResourceManager.GetString("Message_CopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all selected row(s)? (Count : {0}).
        /// </summary>
        internal static string Message_DeleteConfirm {
            get {
                return ResourceManager.GetString("Message_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} row(s) removed..
        /// </summary>
        internal static string Message_DeleteSuccess {
            get {
                return ResourceManager.GetString("Message_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        internal static string Message_Done {
            get {
                return ResourceManager.GetString("Message_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export complete..
        /// </summary>
        internal static string Message_ExportComplete {
            get {
                return ResourceManager.GetString("Message_ExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption error : \n\nThe file {0} could not be opened.\nEither the file is corrupt, or using unknown encryption method / keys..
        /// </summary>
        internal static string Message_FileEncryptionError {
            get {
                return ResourceManager.GetString("Message_FileEncryptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error : table file is not open.
        /// </summary>
        internal static string Message_FileNotOpen {
            get {
                return ResourceManager.GetString("Message_FileNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File open error :\nThe specified table {0} does not exist..
        /// </summary>
        internal static string Message_FileOpenError {
            get {
                return ResourceManager.GetString("Message_FileOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} matching cell(s) replaced.
        /// </summary>
        internal static string Message_NMatchesReplaced {
            get {
                return ResourceManager.GetString("Message_NMatchesReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no checked item(s)!.
        /// </summary>
        internal static string Message_NoCheckedItems {
            get {
                return ResourceManager.GetString("Message_NoCheckedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently no file is open..
        /// </summary>
        internal static string Message_NoFileOpen {
            get {
                return ResourceManager.GetString("Message_NoFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more matches found..
        /// </summary>
        internal static string Message_NoMoreMatches {
            get {
                return ResourceManager.GetString("Message_NoMoreMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No row(s) selected..
        /// </summary>
        internal static string Message_NoRowsSelected {
            get {
                return ResourceManager.GetString("Message_NoRowsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} row(s) are successfully added..
        /// </summary>
        internal static string Message_NRowsAddSuccess {
            get {
                return ResourceManager.GetString("Message_NRowsAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} row(s) copied..
        /// </summary>
        internal static string Message_NRowsCopied {
            get {
                return ResourceManager.GetString("Message_NRowsCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste error..
        /// </summary>
        internal static string Message_PasteError {
            get {
                return ResourceManager.GetString("Message_PasteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste operation failed.\nNo row(s) were copied before..
        /// </summary>
        internal static string Message_PasteNoRows {
            get {
                return ResourceManager.GetString("Message_PasteNoRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait...
        /// </summary>
        internal static string Message_PleaseWait {
            get {
                return ResourceManager.GetString("Message_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made some changes over the table.\nDo you want to commit these changes?\n({0}).
        /// </summary>
        internal static string Message_SaveConfirmChanges {
            get {
                return ResourceManager.GetString("Message_SaveConfirmChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table saved successfully..
        /// </summary>
        internal static string Message_SaveSuccess {
            get {
                return ResourceManager.GetString("Message_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching...
        /// </summary>
        internal static string Message_Searching {
            get {
                return ResourceManager.GetString("Message_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a page first..
        /// </summary>
        internal static string Message_SelectPageFirst {
            get {
                return ResourceManager.GetString("Message_SelectPageFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Title_Information {
            get {
                return ResourceManager.GetString("Title_Information", resourceCulture);
            }
        }
    }
}
